# Generated by Django 4.2.4 on 2023-08-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_lib', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myuser',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='books_Name',
            new_name='books_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_Name',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='users_opened',
            field=models.ManyToManyField(blank=True, related_name='opened_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='books_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
