# Generated by Django 4.2.4 on 2023-08-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0003_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users_opened',
        ),
    ]
