# Generated by Django 4.2.4 on 2023-08-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0005_viewedbook_addedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='AddedBook',
        ),
    ]
