# Generated by Django 4.2.4 on 2023-09-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group_thread_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
